// Generated by CoffeeScript 1.8.0
(function() {
  var GetFav, g, noteStore, token;

  GetFav = require('../lib/getFav');

  noteStore = require('../lib/noteStore');

  token = process.env.daily_zhihu;

  g = new GetFav(token);

  g.getList();

}).call(this);

//# sourceMappingURL=test-getFav.js.map
