// Generated by CoffeeScript 1.10.0
(function() {
  var CheckDaily, PushDaily, ZhihuDaily, async, noteStore, schedule, tx;

  PushDaily = require('../lib/pushDaily');

  ZhihuDaily = require('../models/zhihu_daily');

  async = require('async');

  tx = require('../lib/txErr');

  noteStore = require('../lib/noteStore');

  schedule = require("node-schedule");

  CheckDaily = require('../lib/checkDaily');

  async.waterfall([
    function(cb) {
      var check;
      check = new CheckDaily();
      return check.doTask(cb);
    }, function(cb) {
      return ZhihuDaily.where({
        status: 0
      }).orderBy('id DESC').find(function(err, rows) {
        if (err) {
          return txErr(op.url, {
            err: err,
            fun: 'getList-find'
          });
        }
        return cb(null, rows);
      });
    }, function(tasks, cb) {
      return async.eachSeries(tasks, function(item, callback) {
        var p;
        p = new PushDaily(noteStore, '735b3e76-e7f5-462c-84d0-bb1109bcd7dd', item.url, item.href, item.title);
        return p.pushNote(callback);
      }, function() {
        return console.log("all do");
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=test_daily.js.map
