// Generated by CoffeeScript 1.8.0
(function() {
  var CheckAdd, async, ca, token;

  CheckAdd = require('../lib/checkAdd');

  async = require('async');

  token = process.env.daily_zhihu;

  ca = new CheckAdd(token);

  async.waterfall([
    function(cb) {
      return ca.getList(function(err, data) {
        if (err) {
          return console.log(err);
        }
        return cb(null, data);
      });
    }, function(data, cb) {
      return ca.checkUP(data, function(err) {
        if (err) {
          return console.log(err);
        }
        return console.log("all do");
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=test-check.js.map
