// Generated by CoffeeScript 1.8.0
(function() {
  var PushEvernote, Task, async, noteStore, txErr;

  PushEvernote = require('../lib/PushEvernote');

  Task = require('../models/tasks');

  async = require('async');

  txErr = require('../lib/txErr');

  noteStore = require('../lib/noteStore');

  async.waterfall([
    function(cb) {
      return Task.find({
        status: 1
      }, null, {
        sort: {
          _id: -1
        }
      }, function(err, rows) {
        var i, _i, _len;
        if (err) {
          return txErr(op.url, {
            err: err,
            fun: 'getList-find'
          });
        }
        for (_i = 0, _len = rows.length; _i < _len; _i++) {
          i = rows[_i];
          console.log(i);
        }
        return cb(null, rows);
      });
    }, function(tasks, cb) {
      return async.eachSeries(tasks, function(item, callback) {
        var p;
        p = new PushEvernote(noteStore, '', item.url, item.id, item.title);
        return p.pushNote(callback);
      }, function() {
        console.log("all do");
        return console.log("all do");
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=test_push.js.map
