// Generated by CoffeeScript 1.8.0
(function() {
  var SaveEvernote, async, cheerio, inlineCss, noteStore, request, url;

  request = require('request');

  inlineCss = require('inline-css');

  cheerio = require('cheerio');

  async = require('async');

  SaveEvernote = require('../lib/getArticle');

  noteStore = require('../lib/noteStore');

  url = 'http://daily.zhihu.com/story/4726006';

  async.waterfall([
    function(cb) {
      return request.get(url, function(err, res, body) {
        if (err) {
          return console.log(err);
        }
        return cb(null, body);
      });
    }, function(body, cb) {
      return inlineCss(body, {
        url: 'http://daily.zhihu.com'
      }, function(err, html) {
        if (err) {
          return console.log("err", err);
        }
        return cb(null, html);
      });
    }, function(html, cb) {
      var $, $contentDiv, changHtml;
      $ = cheerio.load(html);
      $contentDiv = $("body");
      if ($contentDiv.length === 0) {
        return console.log("not find content div");
      }
      $(".global-header").remove();
      $("script").remove();
      $("*").map(function(i, elem) {
        var k, v, _ref, _results;
        _ref = elem.attribs;
        _results = [];
        for (k in _ref) {
          v = _ref[k];
          if (k !== 'style' && k !== "src" && k !== "href") {
            _results.push($(this).removeAttr(k));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
      $ = cheerio.load($contentDiv.html());
      changHtml = $.html();
      console.log("changHtml ####################");
      console.log(changHtml);
      console.log("changHtml ####################");
      return cb(null, changHtml);
    }, function(changeHtml, cb) {
      var se;
      se = new SaveEvernote(123, noteStore);
      se.content = changeHtml;
      se.title = "测试";
      return async.series([
        function(callback) {
          return se.changeContent(function(err) {
            if (err) {
              return console.log(err);
            }
            return callback();
          });
        }, function(callback) {
          console.log("createNote");
          console.log(se.enContent);
          return se.createNote(function(err) {
            if (err) {
              return console.log(err);
            }
          });
        }
      ]);
    }
  ]);

}).call(this);

//# sourceMappingURL=test_css.js.map
