// Generated by CoffeeScript 1.10.0
(function() {
  var async, cargo, log;

  async = require('async');

  log = console.log;


  /**
   * 创建cargo实例
   */

  cargo = async.cargo((function(tasks, cb) {
    return async.each(tasks, function(item, callback) {
      console.log("start " + item.name);
      return item.run(function(err) {
        return callback();
      });
    }, function() {
      return cb();
    });
  }), 2);


  /**
   * 监听：如果某次push操作后，任务数将达到或超过worker数量时，将调用该函数
   */

  cargo.saturated = function() {
    log('all workers to be used');
  };


  /**
   * 监听：当最后一个任务交给worker时，将调用该函数
   */

  cargo.empty = function() {
    log('no more tasks wating');
  };


  /**
   * 监听：当所有任务都执行完以后，将调用该函数
   */

  cargo.drain = function() {
    log('all tasks have been processed');
  };

  module.exports = cargo;

}).call(this);

//# sourceMappingURL=cargo.js.map
