// Generated by CoffeeScript 1.8.0
(function() {
  var CheckAdd, Task, async, noteStore, request, txErr;

  request = require('request');

  async = require('async');

  txErr = require('./txErr');

  Task = require('../models/tasks');

  noteStore = require('../lib/noteStore');

  CheckAdd = (function() {
    function CheckAdd(token) {
      this.headers = {
        'Authorization': token
      };
      this.url = 'http://news-at.zhihu.com/api/4/favorites';
    }

    CheckAdd.prototype.getList = function(cb) {
      var op, self;
      self = this;
      op = {
        url: self.url,
        headers: self.headers
      };
      return request.get(op, function(err, res, body) {
        var data;
        if (err) {
          return txErr({
            url: op.url,
            fun: 'getList',
            err: err
          }, cb);
        }
        data = JSON.parse(body);
        console.log("#####################################");
        console.log("find length ==> ", data.stories.length);
        console.log("#####################################");
        return cb(null, data);
      });
    };

    CheckAdd.prototype.checkUP = function(data, cb) {
      var self;
      self = this;
      return async.eachSeries(data.stories, function(item, callback) {
        return Task.findOne({
          id: item.id
        }, function(err, row) {
          if (err) {
            return txErr({
              fun: 'checkUP-find',
              err: err
            }, cb);
          }
          if (row) {
            console.log("find same", row.title, row.id);
            return callback();
          } else {
            return self.addTask(item, function(err, task) {
              if (err) {
                return console.log(err);
              }
              return callback();
            });
          }
        });
      }, function(sErr) {
        if (sErr) {
          return cb(sErr);
        }
        return cb();
      });
    };

    CheckAdd.prototype.addTask = function(taskInfo, cb) {
      var task;
      task = Task();
      task.id = taskInfo.id;
      task.title = taskInfo.title.trim();
      task.url = 'http://daily.zhihu.com/story/' + task.id;
      return task.save(function(err, row) {
        if (err) {
          return txErr({
            fun: 'addTask',
            err: err
          }, cb);
        }
        console.log("已添加：", taskInfo.title, taskInfo.id);
        console.log("\n");
        return cb(null, row);
      });
    };

    return CheckAdd;

  })();

  module.exports = CheckAdd;

}).call(this);

//# sourceMappingURL=checkAdd.js.map
