// Generated by CoffeeScript 1.8.0
(function() {
  var Evernote, GetFav, async, cheerio, crypto, makeNote, request, txErr;

  request = require('request');

  async = require('async');

  txErr = require('./txErr');

  cheerio = require('cheerio');

  Evernote = require('evernote').Evernote;

  crypto = require('crypto');

  makeNote = require('./createNote');

  GetFav = (function() {
    function GetFav(token) {
      this.headers = {
        'Authorization': "Bearer " + token
      };
      this.url = 'http://news-at.zhihu.com/api/4/favorites';
    }

    GetFav.prototype.getList = function() {
      var op, self;
      self = this;
      return op = {
        url: self.url,
        headers: self.headers
      };
    };

    return GetFav;

  })();

}).call(this);

//# sourceMappingURL=getFav.js.map
