// Generated by CoffeeScript 1.10.0
(function() {
  var Daily, PushDaily, PushEvernote, ZhihuDaily, async, noteStore, tx,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  PushEvernote = require('./pushEvernote');

  Daily = require('../models/daily');

  ZhihuDaily = require('../models/zhihu_daily');

  async = require('async');

  tx = require('./txErr');

  noteStore = require('./noteStore');

  PushDaily = (function(superClass) {
    extend(PushDaily, superClass);

    function PushDaily(noteStore1, noteBook, url, id, title) {
      this.noteStore = noteStore1;
      this.noteBook = noteBook;
      this.url = url;
      this.id = id;
      this.title = title;
      PushDaily.__super__.constructor.apply(this, arguments);
    }

    PushDaily.prototype.changeStatus = function(cb) {
      var self;
      self = this;
      return async.waterfall([
        function(callback) {
          return ZhihuDaily.where({
            href: self.id
          }).findOne(function(err, row) {
            if (err) {
              return tx({
                err: err,
                fun: 'changeStatus',
                id: self.id
              }, cb(err));
            }
            if (!row) {
              return tx({
                err: 'data not find',
                id: self.id
              }, cb("not find db"));
            }
            return callback(null, row);
          });
        }, function(row, callback) {
          row.status = 2;
          row.guid = self.guid;
          return row.save(function(err, res) {
            if (err) {
              return tx({
                err: err,
                id: self.id
              }, cb(err));
            }
            return cb();
          });
        }
      ]);
    };

    return PushDaily;

  })(PushEvernote);

  module.exports = PushDaily;

}).call(this);

//# sourceMappingURL=pushDaily.js.map
