// Generated by CoffeeScript 1.8.0
(function() {
  var Daily, PushDaily, PushEvernote, async, noteStore, tx,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PushEvernote = require('./pushEvernote');

  Daily = require('../models/daily');

  async = require('async');

  tx = require('./txErr');

  noteStore = require('./noteStore');

  PushDaily = (function(_super) {
    __extends(PushDaily, _super);

    function PushDaily(noteStore, noteBook, url, id, title) {
      this.noteStore = noteStore;
      this.noteBook = noteBook;
      this.url = url;
      this.id = id;
      this.title = title;
      PushDaily.__super__.constructor.apply(this, arguments);
    }

    PushDaily.prototype.changeStatus = function(cb) {
      var self;
      self = this;
      return async.waterfall([
        function(callback) {
          return Daily.findOne({
            href: self.id
          }, function(err, row) {
            if (err) {
              return tx({
                err: err,
                fun: 'changeStatus',
                id: self.id
              }, cb(err));
            }
            if (!row) {
              return tx({
                err: 'data not find',
                id: self.id
              }, cb("not find db"));
            }
            return callback(null, row);
          });
        }, function(row, callback) {
          row.status = 2;
          return row.save(function(err, res) {
            if (err) {
              return tx({
                err: err,
                id: self.id
              }, cb(err));
            }
            return cb();
          });
        }
      ]);
    };

    return PushDaily;

  })(PushEvernote);

  module.exports = PushDaily;

}).call(this);

//# sourceMappingURL=pushDaily.js.map
