// Generated by CoffeeScript 1.8.0
(function() {
  var SaveEvernote, async, q;

  async = require('async');

  SaveEvernote = require('./getArticle');

  q = async.queue(function(data, cb) {
    var g;
    console.log("" + data.id + " " + data.title + " now do");
    g = new SaveEvernote(data.id, data.noteStore, data.noteBook);
    return async.series([
      function(callback) {
        return g.getInfo(callback);
      }, function(callback) {
        return g.changeContent(callback);
      }, function(callback) {
        return g.createNote(callback);
      }
    ], function(err) {
      if (err) {
        return cb(err);
      }
      return cb();
    });
  }, 1);

  module.exports = q;

}).call(this);

//# sourceMappingURL=queue.js.map
