// Generated by CoffeeScript 1.10.0
(function() {
  var email, txErr;

  email = require('./email')();

  txErr = function(infoJson, cb) {
    var emailBody, k, logInfo, subj, to, v;
    console.error(infoJson.err);
    logInfo = "";
    for (k in infoJson) {
      v = infoJson[k];
      logInfo += k + ": " + v + "\n";
    }
    emailBody = logInfo;
    email.send(emailBody, to = null, subj = 'HI ACE DAILY');
    if (cb) {
      return cb(infoJson.err);
    }
  };

  module.exports = txErr;

}).call(this);

//# sourceMappingURL=txErr.js.map
