// Generated by CoffeeScript 1.8.0
(function() {
  var PushEvernote, UpdateEvernote,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PushEvernote = require('./pushEvernote');

  UpdateEvernote = (function(_super) {
    __extends(UpdateEvernote, _super);

    function UpdateEvernote() {
      return UpdateEvernote.__super__.constructor.apply(this, arguments);
    }

    return UpdateEvernote;

  })(PushEvernote);

}).call(this);

//# sourceMappingURL=updataEvernote.js.map
