// Generated by CoffeeScript 1.10.0
(function() {
  var T, ZhihuDaily, toshihiko;

  T = require("toshihiko");

  toshihiko = require("./toshihiko.js");

  ZhihuDaily = toshihiko.define('zhihu_daily', [
    {
      name: "id",
      type: T.Type.Integer,
      primaryKey: true
    }, {
      name: "href",
      type: T.Type.String,
      defaultValue: ""
    }, {
      name: "url",
      type: T.Type.String,
      defaultValue: ""
    }, {
      name: "guid",
      type: T.Type.String,
      defaultValue: ""
    }, {
      name: "title",
      type: T.Type.String,
      defaultValue: ""
    }, {
      name: "status",
      type: T.Type.Integer,
      defaultValue: "0"
    }, {
      name: "create_time",
      type: T.Type.Integer,
      defaultValue: "0"
    }
  ]);

  module.exports = ZhihuDaily;

}).call(this);

//# sourceMappingURL=zhihu_daily.js.map
